import { FOOD } from './Food';

export const FOODS: FOOD[] = [
  {
    position: 1,
    name: 'Corn',
    fat: 1,
    protein: 3,
    carbohydrates: 19,
    fiber: 3,
  },
  {
    position: 2,
    name: 'Avacado',
    fat: 15,
    protein: 2,
    carbohydrates: 9,
    fiber: 7,
  },
  {
    position: 3,
    name: 'Yams',
    fat: 0,
    protein: 2,
    carbohydrates: 28,
    fiber: 4,
  },
  {
    position: 4,
    name: 'Bananas',
    fat: 0,
    protein: 1,
    carbohydrates: 23,
    fiber: 3,
  },
  {
    position: 5,
    name: 'Peaches',
    fat: 0,
    protein: 1,
    carbohydrates: 10,
    fiber: 1,
  },
  {
    position: 6,
    name: 'Stawberries',
    fat: 0,
    protein: 1,
    carbohydrates: 8,
    fiber: 2,
  },
  {
    position: 7,
    name: 'Almonds',
    fat: 49,
    protein: 21,
    carbohydrates: 22,
    fiber: 12,
  },
  {
    position: 8,
    name: 'Pecans',
    fat: 72,
    protein: 9,
    carbohydrates: 14,
    fiber: 10,
  },
  {
    position: 9,
    name: 'Walnuts',
    fat: 65,
    protein: 15,
    carbohydrates: 14,
    fiber: 7,
  },
  {
    position: 10,
    name: 'Hazelnuts',
    fat: 61,
    protein: 15,
    carbohydrates: 17,
    fiber: 10,
  },
];
